### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by tdatnguyengit** [tdatnguyengit/Z_Assignment#1]
- [x] Design UI/UX
- [x] Code UI with simple slipt function
- [x] Enhance slipt function
